# INTRODUCTION

## Background

Since the publication of ‘The Great Transformation’ (Polanyi, 1957), the concepts of ‘non-economic’ and ‘nonmarket’ successively started to emerge as referring to the internal and external factors that assist markets, firms and other types of institutions and organizations to function efficiently and effectively as well as repair their failures. In the last three decades, studies on the nonmarket field starts to emerge. Among other, the nonmarket field was addressed by Baron (1995), Boddewyn (2003), Hillman (2004), Marcus, Kaufman, and Beam (1987), Preston and Post (1975), Yoffie (1987). However, the definition of nonmarket concept was ambiguous among the various studies. The versatility of the nonmarket concept encouraged Boddewyn (2003) to perform an extensive literature research from various fields of study which provide links to the concept. The roots of nonmarket lie in societal and theoretical choices made over several decades. There exist different perspectives regarding nonmarket, which vary in the way they refer to the internal and external factors that provide order to markets, firms, and other types of institutions and organizations. Four main perspectives provide an adequate overture for the nonmarket concept.

## Problem Statement
## Research Questions
## Objectives
## Significance of Research
## Scope of Research
## Chapter Disposition